### ISSUE TITLE
unable to install with jenssegers/mongodb:dev-develop version

### ISSUE THREAD

**Issue by thewebdepotteam** [mostafamaklad/laravel-permission-mongodb#114]
**Describe the bug**
I'm unable to install this package with the development version of jenssegers/mongodb as of now they don't officially release for laravel 7

**To Reproduce**
1. composer require jenssegers/mongodb:dev-develop
2. composer require mostafamaklad/laravel-permission-mongodb

**Comment by a-zog** [comment]
Same issue here, any updates @mostafamaklad please?

Thanks again for this great package

**Comment by mostafamaklad** [comment]
> ⚠️ ⚡ ⚠️ ⚡ ⚠️  Note: I don't recommend using this solution in production ⚠️ ⚡ ⚠️ ⚡ ⚠️

Now you can use the `v2.1.x-dev` version as I cannot move to final version unless `jenssegers/laravel-mongodb` release his final version first as you know I depend on it 

you can fix your problem using this command 
`composer require mostafamaklad/laravel-permission-mongodb:v2.1.x-dev`
or
`composer update mostafamaklad/laravel-permission-mongodb:v2.1.x-dev`
