### ISSUE TITLE
Support for laravel-mongodb 4

### ISSUE THREAD

**Issue by tomhilgers** [mostafamaklad/laravel-permission-mongodb#115]
Hi,
Im on Laravel 7 with the Alpha Version of laravel-mongodb and your package cant be installed.
I would love to use your package and hope you can add the functionality.

**Comment by Romitou** [comment]
Hi all, I finally found out how to use this package with Laravel 7!
You must install the `dev-develop` version of `jenssegers/mongodb`, and then install the `v2.1.x-dev` version of `mostafamaklad/laravel-permission-mongodb`. I hope this has helped you.

**Comment by mostafamaklad** [comment]
I will provide a release which is supporting Laravel 7 by end of day

**Comment by mostafamaklad** [comment]
Now you can use ``
