### ISSUE TITLE
Call to a member function compileColumnListing() on null

### ISSUE THREAD

**Issue by alex-secondnature** [mostafamaklad/laravel-permission-mongodb#116]
**Describe the bug**
Package won't install and blocks dump-autoload

**To Reproduce**
1. Install
2. Run any command

**Expected behavior**
Not crashing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Brave
 - Version No idea

**Additional context**

```
  Call to a member function compileColumnListing() on null

  at vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:135
    131|      * @return array
    132|      */
    133|     public function getColumnListing($table)
    134|     {
  > 135|         $results = $this->connection->selectFromWriteConnection($this->grammar->compileColumnListing(
    136|             $this->connection->getTablePrefix().$table
    137|         ));
    138| 
    139|         return $this->connection->getPostProcessor()->processColumnListing($results);

      +6 vendor frames 
  7   [internal]:0
      Maklad\Permission\Models\Permission::__construct()

      +20 vendor frames 
  28  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

```

**Comment by a-zog** [comment]
Same issue here

**Comment by mostafamaklad** [comment]
could you share your `composer.json` file

**Comment by alex-secondnature** [comment]
It's because you're calling `parent::_construct()` in the `__construct()` method of`Models/Permission.php`. It's attempting to auto-generate a list of guarded attributes using the `$table` property, and it sets it after the constructor is called. Remove the call to super/parent and it's fine. I had to copy/paste the model into a new custom one and change the source in config.

**Comment by nabad600** [comment]
Same issue here

**Comment by anangmaruf** [comment]
same issue here, how i solve the problem?

**Comment by sfx101** [comment]
Downgrade Laravel's minor version to solve the issue instantly 
Most probably near 6.18.2 Laravel release, the dependencies create the fatal error

```
composer.json
"laravel/framework": "^6.2" -> "laravel/framework": "6.2",
```
This is not the perfect solution and can be used as long as @mostafamaklad does not have patch ready

**Comment by phyothiha** [comment]
@sfx101 How long have you been using this package? I'm start using right now and this package is updated since 2 years ago. Is it reliable.

**Comment by a-zog** [comment]
> It's because you're calling `parent::_construct()` in the `__construct()` method of`Models/Permission.php`. It's attempting to auto-generate a list of guarded attributes using the `$table` property, and it sets it after the constructor is called. Remove the call to super/parent and it's fine. I had to copy/paste the model into a new custom one and change the source in config.

@alex-secondnature thank you for the input
@mostafamaklad Any idea on when we could deploy this patch please as a lot of projects depend on it?  Great work with this package by the way

**Comment by Mr-Kiany** [comment]
Same issue here too

**Comment by rathaurashish** [comment]
> It's because you're calling `parent::_construct()` in the `__construct()` method of`Models/Permission.php`. It's attempting to auto-generate a list of guarded attributes using the `$table` property, and it sets it after the constructor is called. Remove the call to super/parent and it's fine. I had to copy/paste the model into a new custom one and change the source in config.

If this changes are done then throw many errors, Query not run, guard not save etc, pls give permanent solution.

**Comment by aekanshpartani** [comment]
Facing the same issue when I tried creating the role.
Anyone came up with proper fix?
Also is this package maintained or not @mostafamaklad

**Comment by mostafamaklad** [comment]
Sorry for the late response
@alex-secondnature @a-zog @anangmaruf @sfx101 @phyothiha @Mr-Kiany @rathaurashish @aekanshpartani
I will release the new update by end of day and will support Laravel 7 as well.

if you have any updates you can create a pull request and I will approve it.
