### ISSUE TITLE
assignRole not working in laravel 8

### ISSUE THREAD

**Issue by ovis-it** [mostafamaklad/laravel-permission-mongodb#123]
Hi, 
i got an error in a fresh installed laravel with mongodb.
I use the seeder looks like so:
`<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Illuminate\Support\Str;
//use Spatie\Permission\Models\Role;
use App\Models\User;
use App\Models\RoleHierarchy;
use Maklad\Permission\Models\Role;
use Maklad\Permission\Models\Permission;

class UsersAndNotesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $connection = 'mongodb';

    public function run()
    {
        $numberOfUsers = 10;
        $numberOfNotes = 5000;
        $usersIds = array();
        $statusIds = array();
        $userStatus = array(
            'Active',
            'Inactive',
            'Pending',
            'Banned'
        );
        app()['cache']->forget('maklad.permission.cache');

        $role = Role::firstOrCreate(['name' => 'admin']);
        $role = Role::firstOrCreate(['name' => 'user']);
        $role = Role::firstOrCreate(['name' => 'guest']);

        /*  insert status  */
        DB::table('status')->insert([
            '_id' => 'ongoing',
            'name' => 'ongoing',
            'class' => 'primary',
        ]);
        array_push($statusIds, 'ongoing');
        DB::table('status')->insert([
           '_id'=> 'stopped',
            'name' => 'stopped',
            'class' => 'secondary',
        ]);
        array_push($statusIds, 'stopped');
        DB::table('status')->insert([
            '_id'=>'completed',
            'name' => 'completed',
            'class' => 'success',
        ]);
        array_push($statusIds, 'completed');
        DB::table('status')->insert([
            '_id'=> 'warning',
            'name' => 'expired',
            'class' => 'warning',
        ]);
        array_push($statusIds, 'warning');
        /*  insert users   */
        $user = User::create([
            'name' => 'admin',
            'email' => 'admin@admin.com',
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Str::random(10),
            'menuroles' => 'user,admin',
            'status' => 'Active'
        ]);

        $user->assignRole('admin');
        $user->assignRole('user');
    }
}

`

if i run this seeder i get this error:

   `Error 

  Call to a member function prepare() on null

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:331
    327▕             // For select statements, we'll simply execute the query and return an array
    328▕             // of the database result set. Each element in the array will be a single
    329▕             // row from the database table, and will either be an array or objects.
    330▕             $statement = $this->prepared(
  ➜ 331▕                 $this->getPdoForSelect($useReadPdo)->prepare($query)
    332▕             );
    333▕ 
    334▕             $this->bindValues($statement, $this->prepareBindings($bindings));
    335▕ 

      +13 vendor frames 
  14  [internal]:0
      App\Models\User::Maklad\Permission\Traits\{closure}()

      +2 vendor frames 
  17  database/seeders/UsersAndNotesSeeder.php:76
      App\Models\User::assignRole()`

the mongodb driver is installed and it works. the admin user is insert in the collection user.
ANY Ideas? 
THX
THomas

**Comment by mostafamaklad** [comment]
Please make sure that the `User` Model is extending `\Jenssegers\Mongodb\Eloquent\Model`
