### ISSUE TITLE
No query results for model

### ISSUE THREAD

**Issue by sajadjanat** [mostafamaklad/laravel-permission-mongodb#124]
Hi, I install this package and when i want give permission to role or assign a role to user laravel throw me this exception :
 "message": "No query results for model [Maklad\\Permission\\Models\\Role] admin",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "D:\\...\\...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php",
    "line": 381,
thanks for helping me.

**Comment by makladuxbert** [comment]
Please make sure that you have created the role that you are assigning to

**Comment by mostafamaklad** [comment]
Please make sure that you have created the role that you are assigning to
