### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by anony253** [mostafamaklad/laravel-permission-mongodb#133]

**Comment by peterkeri** [comment]
Hi, i cant try with laravel9 yet. Is there any problem if I update Laravel? thanks for reply!

**Comment by saad-bearplex** [comment]
Any luck?

**Comment by teamelliel** [comment]
Any fix for Laravel 9?

**Comment by w99910** [comment]
For **Laravel 9**, 
- Update package version to 'v4.0.x-dev' in your composer json file. 
`"mostafamaklad/laravel-permission-mongodb": "v4.0.x-dev",`
- Run `composer update`
