### ISSUE TITLE
MongoDB\BSON\ObjectID

### ISSUE THREAD

**Issue by hoangcao10** [mostafamaklad/laravel-permission-mongodb#35]
laravel 5.4 when run php artisan got the error:
[Exception]                                              
  Serialization of 'MongoDB\BSON\ObjectID' is not allowed

**Comment by mostafamaklad** [comment]
It is because of the mongodb driver version you have to update it 
[mongodb/mongo-php-library#150](https://github.com/mongodb/mongo-php-library/issues/150)
