### ISSUE TITLE
 " Serialization of 'MongoDB\BSON\ObjectID' is not allowed "when trying to seed error

### ISSUE THREAD

**Issue by ariefruf** [mostafamaklad/laravel-permission-mongodb#42]
I am quite beginner on this programming

The environment
16.04.3 LTS
laravel 5.5

**Comment by mostafamaklad** [comment]
Could you check your mongodb driver?
you could use this reference [Installing the MongoDB PHP Driver with PECL](http://php.net/manual/en/mongodb.installation.pecl.php)
