### ISSUE TITLE
Error trying to install the package

### ISSUE THREAD

**Issue by TresCe** [mostafamaklad/laravel-permission-mongodb#53]
Hello, I'm trying to install this package, but I'm getting the following error.

```
In Builder.php line 135:

  Type error: Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection give
  n, called in C:\Users\TresCe\Documents\Proyectos\Aquasis\vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Eloquent\Model.php on line 412
```

Before installing this package https://github.com/jenssegers/laravel-mongodb
Laravel: 5.5
O.S .: Windows 10
PHP: 7.1.1
Somebody could help me?

**Comment by mostafamaklad** [comment]
could you install jenssegers/laravel-mongodb first and tell me if the issue still exists 
if it exists check your user model make sure it extends Jenssegers\Mongodb\Eloquent\Model

**Comment by TresCe** [comment]
Before installing [laravel-permission-mongodb](https://github.com/mostafamaklad/laravel-permission-mongodb), should I change the model extension?

**Comment by Giacomo92** [comment]
I have also found this error, I think you should add this:

> could you install jenssegers/laravel-mongodb first and tell me if the issue still exists
if it exists check your user model make sure it extends Jenssegers\Mongodb\Eloquent\Model

on readme just before the 

`composer require mostafamaklad/laravel-permission-mongodb`

@mostafamaklad

**Comment by mostafamaklad** [comment]
Yes you have to extend from `Jenssegers\Mongodb\Eloquent\Model `
