### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Giacomo92** [mostafamaklad/laravel-permission-mongodb#64]
When I try to install I get this error:

> In PermissionRegistrar.php line 36:
  Type error: Argument 1 passed to Maklad\Permission\PermissionRegistrar::Mak
  lad\Permission\{closure}() must be an instance of Maklad\Permission\Models\
  Permission, instance of Spatie\Permission\Models\Permission given

This is my user model:
      
    namespace App\Models\Auth\User;

    use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

    use Jenssegers\Mongodb\Eloquent\SoftDeletes;

    class User extends MDModel{   
       protected $connection = 'mongodb';

       protected $table = 'users';

       use SoftDeletes;

       protected $dates = ['deleted_at', 'created_at', 'updated_at'];

    }
I have also created the _users_ collection on the DB

How can I fix this?

**Comment by mostafamaklad** [comment]
Hello ,

First you model must extends from `Jenssegers\Mongodb\Eloquent\Model `
Second you have to use `HasRoles` Trait 
Third, use `Maklad\Permission\Models
Permission` instead of `Spatie\Permission\Models\Permission` in `config/permission.php`

 ```php
namespace App\Models\Auth\User;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Maklad\Permission\Traits\HasRoles;

class User extends Eloquent{   
   protected $connection = 'mongodb';

   protected $table = 'users';

   use SoftDeletes;
   use HasRoles;

   protected $dates = ['deleted_at', 'created_at', 'updated_at'];

}
```

**Comment by Giacomo92** [comment]
My problem was due to the preesistent version of Laravel Permission by Spatie conflict with the new installation. After I cleaned my project all it is working. 
Thank you @mostafamaklad

**Comment by mostafamaklad** [comment]
You are welcome @Giacomo92
