### ISSUE TITLE
Assign permissions to a role, and a role to a user

### ISSUE THREAD

**Issue by chanwix** [mostafamaklad/laravel-permission-mongodb#67]
Hi, I installed your package successfully and I can create roles & permissions with no problem, from a terminal with artisan and also from the frontend form. But when I try to assign a certain role to a user or a permission to a role the database remains the same, the user collection doesn't update, either permissions & roles collections (no intermediate collections like user_has_roles or roles_has_permissions).  I replicated the readme with no success, any suggestion? Thanks in advance, best regards

**Comment by mostafamaklad** [comment]
Could you check the DB connection like querying anything from the DB?

Or flush the cache using `php artisan cache:clear`

**Comment by chanwix** [comment]
I flushed the cache and I can assign permissions to roles and roles to users, but only programatically. If I use the forms that I've created they don't update the documents in the db, I've started to work with users, roles & permissions controllers really similar to what people do with the Spatie plugin, but they don't update at all.

**Comment by chanwix** [comment]
ok solved!!! my fault!! It was because of the validator, I wasn't displaying the errors, then I didn't know what was happening at any moment. Anyway, thanks for your help!
