### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by matteo030** [mostafamaklad/laravel-permission-mongodb#69]
When i run the composer require command, it installs the package but when generating optimized autoload files i get this error:
> In PermissionRegistrar.php line 35:
>Type error: Argument 1 passed to Maklad\Permission\PermissionRegistrar::Maklad\Permission\{closure}()must be an instance of Maklad\Permission\Contracts\PermissionInterface, instance of __PHP_Incomplete_Class given.

 And whatever page of the application i try to visit i get the above error message.

The config/permission.php is published.
My User Model: 
```
namespace App\Models\Auth\User;

use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Model;
use Maklad\Permission\Traits\HasRoles;

class User extends Model
{
    use HasRoles, Authenticatable;

    protected $table = 'users';

    protected $connection = 'mongodb';
	
	protected $dates = ['deleted_at', 'created_at', 'updated_at'];

}

```
Does anyone know how to solve this?

Edit: Laravel 5.5

**Comment by mostafamaklad** [comment]
check if you install spatie/laravel-permission
if you installed it remove it by
`composer remove spatie/laravel-permission`
