### ISSUE TITLE
role relation does not get updated after assigning role

### ISSUE THREAD

**Issue by anthonyvancauwenberghe** [mostafamaklad/laravel-permission-mongodb#73]
consider the following example:

```
public function testRoles()
    {
        $user = User::first();
        $this->assertFalse($user->hasRole('admin'));
        $user->assignRole('admin');
        $this->assertTrue($user->hasRole('admin'));
    }
```

The second assertion fails. I'm not sure if there's something wrong with the laravel internals, the jenssegers library or yours didn't go in depth. But atleast i fixed it for now by adding

`unset($this->roles);`

add the end of the assignrole method.

Do you have any idea @mostafamaklad what's causing this?

**Comment by ludo1960** [comment]
I think i've got the same issue, I have 1 user (admin) in the database. When I try 
$user = User::where('name', '=', 'admin')->get();
$user->assignRole('super-admin');
I get the following error:
1) Tests\Feature\UserTest::testExample
BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::assignRole does not exist.

Then when I try:
$user = User::first();
$user->assignRole('super-admin');
It works as it is supposed to do ie: the role_id column in the user collection is populated, any ideas?

**Comment by mostafamaklad** [comment]
you have to use the trait 
`use HasRoles;`
in your model `User`

**Comment by ludo1960** [comment]
My User Model is as per the documentation:

namespace App;

use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Model;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Maklad\Permission\Traits\HasRoles;


class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable, HasRoles;

---------------------------------------------------------------------------------

I used php artisan make:test UserTest, and in UserTest I put:

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Maklad\Permission\Models\Role;
use Maklad\Permission\Models\Permission;
use App\User;

class UserTest extends TestCase
{
    public function setUp()
    {
        // first include all the normal setUp operations
        parent::setUp();

         // now re-register all the roles and permissions
        $this->app->make(\Maklad\Permission\PermissionRegistrar::class)->registerPermissions();

        $user = User::where('name', 'admin')->get();
        $user->assignRole('super-admin');

    }

}

**Comment by ludo1960** [comment]
Then in terminal I run vendor/bin/phpunit and get:
There was 1 error:
1) Tests\Feature\UserTest::testExample
BadMethodCallException: Method Illuminate\Database\Eloquent\Collection::assignRole does not exist.

**Comment by AngusDV** [comment]
after assignRole just use $user->save(); my problem solved with this way.
