### ISSUE TITLE
database migration

### ISSUE THREAD

**Issue by ludo1960** [mostafamaklad/laravel-permission-mongodb#75]
hello,
it would be very handy to have a recommended db migration or is the migration the same as in the ui link to spatie that you listed?

many thanks for your work on this project!

**Comment by mostafamaklad** [comment]
Thanks for your response 
Will do it very soon soon

**Comment by ludo1960** [comment]
i will make new tutorial for ui to add to your project if you want.

thank you for your response

**Comment by ludo1960** [comment]
This might make your task easier [Mostafa] (https://github.com/jenssegers/Laravel-MongoDB-Sentry)

**Comment by mostafamaklad** [comment]
We have added the migration files in version 1.10.0
