### ISSUE TITLE
version 1.10.0

### ISSUE THREAD

**Issue by ludo1960** [mostafamaklad/laravel-permission-mongodb#79]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ludo1960** [comment]
Hi Guys,

Fresh install laravel 5.7 Jenssegers MongoDB latest all working perfectly. Then from terminal "composer require mostafamaklad/laravel-permission-mongodb" after download I check the composer.json and to my surprise the it says "mostafamaklad/laravel-permission-mongodb": "^1.9"
so I change it to 1.10.0 and run composer update then I run "php artisan vendor:publish --provider="Maklad\Permission\PermissionServiceProvider" --tag="migrations"
then php artisan migrate
then publish the php artisan vendor:publish --provider="Maklad\Permission\PermissionServiceProvider" --tag="config"
Followed the documentation for adding use Maklad\Permission\Traits\HasRoles; to the the User.php
Then followed documentation to add middleware:
protected $routeMiddleware = [
    // ...
    'role' => \Maklad\Permission\Middlewares\RoleMiddleware::class,
    'permission' => \Maklad\Permission\Middlewares\PermissionMiddleware::class,
];
In the app/Http/Kernel.php file.

Then in my controller for my post model I entered "        $this->middleware(['role:super-admin','permission:publish posts|edit posts']);

Result:  ReflectionException (-1) Class role does not exist
/var/www/laramongo.local.com/vendor/laravel/framework/src/Illuminate/Container/Container.php
    }
 
    /**
     * Instantiate a concrete instance of the given type.
     *
     * @param  string  $concrete
     * @return mixed
     *
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function build($concrete)
    {
        // If the concrete type is actually a Closure, we will just execute it and
        // hand back the results of the functions, which allows functions to be
        // used as resolvers for more fine-tuned resolution of these objects.
        if ($concrete instanceof Closure) {
            return $concrete($this, $this->getLastParameterOverride());
        }
 
        $reflector = new ReflectionClass($concrete);
 
        // If the type is not instantiable, the developer is attempting to resolve
        // an abstract type such as an Interface of Abstract Class and there is
        // no binding registered for the abstractions so we need to bail out.
        if (! $reflector->isInstantiable()) {
            return $this->notInstantiable($concrete);
        }
 
        $this->buildStack[] = $concrete;
 
        $constructor = $reflector->getConstructor();
 
        // If there are no constructors, that means there are no dependencies then
        // we can just resolve the instances of the objects right away, without
        // resolving any other types or dependencies out of these containers.
        if (is_null($constructor)) {
            array_pop($this->buildStack);
 
            return new $concrete;
        }
Arguments
"Class role does not exist"

**Comment by mostafamaklad** [comment]
update 
`"mostafamaklad/laravel-permission-mongodb": "^1.9"`
to 
`"mostafamaklad/laravel-permission-mongodb": "^1.10"`
in your composer file 
then run `composer update`

**Comment by ludo1960** [comment]
Yeah, that works! Thanks guys!
