### ISSUE TITLE
AssignRole at user creation stage

### ISSUE THREAD

**Issue by ludo1960** [mostafamaklad/laravel-permission-mongodb#82]
**Describe the bug**
Unable to AssignRole on user creation
**To Reproduce**
    public function create() {
    //Get all roles and pass it to the view
        $roles = Role::get();
        return view('users.create', ['roles'=>$roles]);
    }
    public function store(Request $request) {
    //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:40',
            'email'=>'required|email',
            'password'=>'required|min:6|confirmed'
        ]);

        $roles = $request['roles']; //Retrieving the roles field
        $user = User::create($request->only('email', 'name', 'password'));

         if (isset($roles)) {
            foreach ($roles as $role) {
                $role_r = Role::where('_id', '=', $roles)->get()->pluck('name');
                $user->assignRole($role_r);
            }
         }
**Expected behavior**
The $role_r should be assigned to newly created User
**Screenshots**

**Desktop (please complete the following information):*
debian  9.4
maklan   permissions 1.10

**Smartphone (please complete the following information):**

**Additional context**
It seems the $role_r is not available (ie empty) because the new user does not have the HasRoles trait applied to it on creation. Once the user is created, a visit to an edit form applies the roles permissions etc with no problems

**Comment by mostafamaklad** [comment]
Please check your variable names


```php
$roles = $request['roles']; //Retrieving the roles field
$user = User::create($request->only('email', 'name', 'password'));

if (isset($roles)) {
  foreach ($roles as $role) {
    $role_r = Role::where('_id', '=', $role)->first()->name;
    $user->assignRole($role_r);
  }
}
````
