### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by LukeJohnson90** [mostafamaklad/laravel-permission-mongodb#87]
**Describe the bug**
I am trying to install this package but when i try to install i get the following error:

In Container.php line 779:

  Class Spatie\Permission\Models\Permission does not exist

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with err
or code 1

I have tried installing the spatie package before hand with no success, as the error i get then is the following:
In Connection.php line 326:

  Call to a member function prepare() on null

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with err
or code 

Due to this error after installing, i get the error when trying to run php artisan serve and the only way to get this working again is to uninstall the package.

I have been trying to get this to work for hours now with no success. do you have any ideas, i'm at my wits end.

**Comment by McMazalf** [comment]
@LukeJohnson90 you need to delete the "permission.php" file that spatie generated before. When you run composer remove your/package it doesen't remove those kind of files. So to proceed you need to delete "`config/permission.php`". Hope this will help you
