### ISSUE TITLE
user_ids in roles table

### ISSUE THREAD

**Issue by moazam1** [mostafamaklad/laravel-permission-mongodb#92]
I have over 300K+ users and I concerned about the performance issues. You are storing user_ids in the roles table: https://www.screencast.com/t/hsvxMs4M and queries like Role::where('name','user')->get() will kill server unless we exclude user_ids column. 

I suggest that you move them to a separate table.

**Comment by moazam1** [comment]
@mostafamaklad would love to hear your thoughts. Thanks

**Comment by henryonsoftware** [comment]
@moazam1 I think what he does like that follows the correct concept of Mongo DB.

**Comment by mostafamaklad** [comment]
@moazam1 I have fixed the relationship issue,
could you please help in reviewing it?
