### ISSUE TITLE
Installation failed in laravel 6.0

### ISSUE THREAD

**Issue by sayaqwe97** [mostafamaklad/laravel-permission-mongodb#98]
I have error installation this package
Installation failed, reverting ./composer.json to its original content.

**Comment by mostafamaklad** [comment]
`jenssegers/laravel-mongodb` still not supporting `Laravel 6.0`
when it will be available we will support it

**Comment by apascualm** [comment]
Hello @mostafamaklad,

Laravel 6.0 support was released, but it is not a comment in the Readme file, however, it is not mentioned in the compatibility table.

https://github.com/jenssegers/laravel-mongodb/pull/1823

**Comment by moazam1** [comment]
@mostafamaklad any update?

**Comment by jampzo** [comment]
> @mostafamaklad any update?

PLS
